language: node_js
node_js: '10'
cache: yarn
git:
  depth: 3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
  - NODE_ENV=test
script:
- yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: heroku
  app: missed-connections-client
  api_key:
    secure: LlTZE7sxGsBWN9JkNTBg5YJwq7tKeX82wHUNckNIoVZ8dh33NalVaazcO/AH3ci5XS3eXcPwvu9xmLTmRDNgIdwIqUsUXCcaIBBzeubbZEg0ekPNY92y/gjQID55KgyNK7aoKyrA4Mt5LIHjQd3kURqAwMB2na7UOw+crzDfKqY0hF/kWggCquoamcOYfVYu8st+9W17/ER2Lh3jPAm90vqM6S7MVyp5dwOCoNWfZbMI4lKoh6q/Lke4zFsoAOXN6+xmmPrQ7IcbCZyJVuYAHP85wfu4p/5fPxapbj9vPwvMheHKFHYV5+3LbPar/8m6O3u3uCZAiCsUgQOrHb1GIbdNHoCVSHtMn0HVqESNBlpJvwlt0AyynEhdetUT/QVeCjUSCEJx38Fd93sEd71QJ1hT6Ali/RoG9iKS6XY44C13cx9EBDktUk3im04OwlhcBszqTc6D2/WMeDyiJoghSBYwhbRf9uAGUPb8O+vFLkeOQGtz0WE86PrTwdJJjkvRe3m5bULF6nrN0kuCMn/olFs37qdBOUoIqw6GBRlrbCGtEDKFIzUKti8dq7p9Pw2Vg1JfRphz1wiqb0SvQG3cSfMe0RUEPr4ed5OT45nVQc0WjFm9wjQJoaOYbrWCTXIsJhIedOrBaIEk1+rB++qylmGbzlgnAs04CE9kAnFYV40=
