language: node_js
node_js: '10'
cache: yarn
git:
  depth: 3
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
  - NODE_ENV=test
script:
- yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: heroku
  app: missed-connections-client
  api_key:
    secure: sMVGGfPiuFiToI+l8+HCD2EMMlsNI6uZ+e5foKHJsHPICLJ4P0xFQofUHVCNCegz3Mi9VXP/WiMjjLLn8f9CASzlHmjDaO2katMHV1RcCA52Ulu6BamGEqewKJLe2tAZEcws1fOpy9neVnzHOwZwFyMIhizF08fLlPcfevxyfl+rBzJL57PqEXwbjAxlLkIXg1qk3Vc/PgiAbxb0iacs92zHdkH/9Nlb9LPeJ39B2QPkeLcAPyMeDez1DbB9Aidan3bYHY2tacvbi6yPQqDirAr9zYEQBvI7SN5RaSspEUw75OiLRERCXny2aLKVME3SOxFTJ01GhbiBbaL8MjXTpuYsdyyhLZg67e0QDD1tGRxUwPtM06fDYmryqw2uuYB/NhPcj/AHAVhtj00hmBxqFugY8LThb6Y8tIy14lyfKi7W6TjWis6GHI5r6U9ZjiADRo45S9aSe1766cebjEAJf4PailPlXueBPuVtj+CYIlQjcTL//5S9n8Z+5B0gDLMEbSF4WTwLYZBDNmPfVRf+dmUKrIkkcDXCSjEgApp/DIW6xrIganZQBPaHF8TTcDcoWqxIPtuKGhFiBXQIVfxCt5nHUaqewuUFpVKl0yHJpdZv6Jg/G7ZNIazzmtdd7s9wxe1/rQYIamyS2WIj8jb1lGEYxtvflzYxlYXn7752EN0=
